// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFBMgLX_isB1wYbAPO42nmjB_57JeiEKA',
    appId: '1:991921086434:web:8ab6f89f57c20aa4f6a3bb',
    messagingSenderId: '991921086434',
    projectId: 'bookly-81f7c',
    authDomain: 'bookly-81f7c.firebaseapp.com',
    storageBucket: 'bookly-81f7c.firebasestorage.app',
    measurementId: 'G-LQB7E8E30E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiPCult5xFYU2tVwv8AmWgIZke0MERhHA',
    appId: '1:991921086434:android:c8658e944284598df6a3bb',
    messagingSenderId: '991921086434',
    projectId: 'bookly-81f7c',
    storageBucket: 'bookly-81f7c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQeiDR-BcU_0PMMOF7Sdk5sgBHkEiYjsg',
    appId: '1:991921086434:ios:cd68f7fc3a177fc3f6a3bb',
    messagingSenderId: '991921086434',
    projectId: 'bookly-81f7c',
    storageBucket: 'bookly-81f7c.firebasestorage.app',
    iosBundleId: 'com.example.bookly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQeiDR-BcU_0PMMOF7Sdk5sgBHkEiYjsg',
    appId: '1:991921086434:ios:cd68f7fc3a177fc3f6a3bb',
    messagingSenderId: '991921086434',
    projectId: 'bookly-81f7c',
    storageBucket: 'bookly-81f7c.firebasestorage.app',
    iosBundleId: 'com.example.bookly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFBMgLX_isB1wYbAPO42nmjB_57JeiEKA',
    appId: '1:991921086434:web:d27debc7909ee064f6a3bb',
    messagingSenderId: '991921086434',
    projectId: 'bookly-81f7c',
    authDomain: 'bookly-81f7c.firebaseapp.com',
    storageBucket: 'bookly-81f7c.firebasestorage.app',
    measurementId: 'G-VTQCK9DSWJ',
  );
}
